name: Cypress Automation Test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps: 
       - uses: actions/checkout@v2
       - run: npm test